-- U-dite Phase 1 database
-- Run this in Supabase SQL Editor.

create type public.user_role as enum ('student', 'lecturer', 'admin');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  role public.user_role not null default 'student',
  student_number text unique,
  programme text,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table public.courses (
  id bigint generated by default as identity primary key,
  code text not null unique,
  title text not null,
  description text,
  lecturer_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.enrollments (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  semester text not null,
  created_at timestamptz not null default now(),
  unique(student_id, course_id, semester)
);

create table public.assignments (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null,
  description text,
  due_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.submissions (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  file_url text,
  submitted_at timestamptz not null default now(),
  grade numeric,
  feedback text,
  unique(assignment_id, student_id)
);

create table public.exams (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  exam_date date not null,
  start_time time,
  end_time time,
  venue text,
  created_at timestamptz not null default now()
);

create table public.results (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  marks numeric check (marks >= 0 and marks <= 100),
  grade text,
  points numeric,
  semester text not null,
  created_at timestamptz not null default now(),
  unique(student_id, course_id, semester)
);

create table public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  body text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

-- Automatically create a student profile after signup.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role, student_number, programme)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
     'student', nullif(new.raw_user_meta_data ->> 'student_number', ''), nullif(new.raw_user_meta_data ->> 'programme', '')
  );
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Row Level Security
alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.enrollments enable row level security;
alter table public.assignments enable row level security;
alter table public.submissions enable row level security;
alter table public.exams enable row level security;
alter table public.results enable row level security;
alter table public.announcements enable row level security;
alter table public.notifications enable row level security;

create policy "users can read own profile"
on public.profiles for select to authenticated
using (id = auth.uid());

create policy "users can update own profile"
on public.profiles for update to authenticated
using (id = auth.uid());

create policy "authenticated users can read courses"
on public.courses for select to authenticated
using (true);

create policy "students can read own enrollments"
on public.enrollments for select to authenticated
using (student_id = auth.uid());

create policy "students can read assignments for enrolled courses"
on public.assignments for select to authenticated
using (
  exists (
    select 1 from public.enrollments e
    where e.course_id = assignments.course_id
      and e.student_id = auth.uid()
  )
);

create policy "students can read own submissions"
on public.submissions for select to authenticated
using (student_id = auth.uid());

create policy "students can create own submissions"
on public.submissions for insert to authenticated
with check (student_id = auth.uid());

create policy "students can update own submissions"
on public.submissions for update to authenticated
using (student_id = auth.uid());

create policy "students can read exams for enrolled courses"
on public.exams for select to authenticated
using (
  exists (
    select 1 from public.enrollments e
    where e.course_id = exams.course_id
      and e.student_id = auth.uid()
  )
);

create policy "students can read own results"
on public.results for select to authenticated
using (student_id = auth.uid());

create policy "authenticated users can read announcements"
on public.announcements for select to authenticated
using (true);

create policy "users can read own notifications"
on public.notifications for select to authenticated
using (user_id = auth.uid());

create policy "users can update own notifications"
on public.notifications for update to authenticated
using (user_id = auth.uid());
